### PR TITLE
Hide build buttons in Multibranch branch/PR jobs when the Multibranch or organization folder is disabled

### LINKED ISSUE #16678: [JENKINS-75417] Scheduling build under disabled Multibranch folder says "Build Scheduled" while it is not scheduled
<p>When trying to trigger a build of a branch job of a *<b>disabled</b>* Multibranch project, the build is not scheduled (because the multibranch is disabled) but a UI notification pop up shows "Build Scheduled".</p>

<p> <span class="image-wrap" style=""><a id="64087_thumb" href="https://issues.jenkins.io/secure/attachment/64087/64087_build-scheduled-msg-while-it-is-not.png" title="build-scheduled-msg-while-it-is-not.png" file-preview-type="image" file-preview-id="64087" file-preview-title="build-scheduled-msg-while-it-is-not.png"></a></span> </p>

<p>Note: The developer console shows that the request to <tt>/build?delay=0</tt> returns a <tt>302</tt>. Whereas in a case where the build is actually scheduled we get a <tt>201</tt>.</p>

<h3><a name="HowtoReproduce"></a>How to Reproduce</h3>

<ul>
	<li>Create a Multibranch pipeline</li>
	<li>Disable the Multibranch Pipeline (through its configuration page or <tt>/disable</tt>)</li>
	<li>try to build a branch job</li>
</ul>

---
<details><summary><i>Originally reported by  <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=allan_burdajewicz">allan_burdajewicz</a>, imported from: <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-75417" target="_blank">Scheduling build under disabled Multibranch folder says "Build Scheduled" while it is not scheduled</a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Major
<li><b>component(s)</b>: cloudbees-folder-plugin, core
<li><b>resolution</b>: Unresolved
<li><b>votes</b>: 0
<li><b>watchers</b>: 1
<li><b>imported</b>: 2025-11-24
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p>When trying to trigger a build of a branch job of a *<b>disabled</b>* Multibranch project, the build is not scheduled (because the multibranch is disabled) but a UI notification pop up shows "Build Scheduled".</p>

<p> <span class="image-wrap" style=""><a id="64087_thumb" href="https://issues.jenkins.io/secure/attachment/64087/64087_build-scheduled-msg-while-it-is-not.png" title="build-scheduled-msg-while-it-is-not.png" file-preview-type="image" file-preview-id="64087" file-preview-title="build-scheduled-msg-while-it-is-not.png"></a></span> </p>

<p>Note: The developer console shows that the request to <tt>/build?delay=0</tt> returns a <tt>302</tt>. Whereas in a case where the build is actually scheduled we get a <tt>201</tt>.</p>

<h3><a name="HowtoReproduce"></a>How to Reproduce</h3>

<ul>
	<li>Create a Multibranch pipeline</li>
	<li>Disable the Multibranch Pipeline (through its configuration page or <tt>/disable</tt>)</li>
	<li>try to build a branch job</li>
</ul>
</pre>
</details>
</details>
<ul><li><i>environment</i>: <code>core:2.501</code></li></ul>
<details><summary><i>1 attachment</i></summary>

- [build-scheduled-msg-while-it-is-not.png](https://raw.githubusercontent.com/jenkinsci/attachments-from-jira-issues-core-cli/refs/heads/main/attachments/64087/build-scheduled-msg-while-it-is-not.png)
  > 
</details>

### PR DESCRIPTION
**Pull request by mawinter69**
When disabling a Multibranch project the branch/PR jobs still show the build button in the sidepanel and in the folder view the Build button column allows to start a build.

By adding the isBuildable to the BuildableItem interface we can now detect in Jobs if the parent is disabled. This will then hide the build button in the sidepanel and the column in the view.

Fixes #16678

### Testing done
Created a multibranch job that has one branch and one PR
disabled Multibranch project -> the jobs for the branch and PR no longer show the `Build Now` button in the sidepanel and in the view the Build Button column has no button anymore.

Did the same for an Organization folder

#### After
Multibranch Job disabled:
image
main branch job without `Build Now`button
image

Multibranch Job Enabled:
image

Multibranch project in a Disabled org:
image

### Proposed changelog entries

- Hide build buttons in Multibranch branch/PR jobs when the Multibranch or organization folder is disabled

### Proposed changelog category

/label bug

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [x] The issue, if it exists, is well-described.
- [x] The changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developers, depending on the change) and are in the imperative mood (see [examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)). Fill in the **Proposed upgrade guidelines** section only if there are breaking changes or changes that may require extra steps from users during upgrade.
- [ ] There is automated testing or an explanation as to why this change has no tests.
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadocs, as appropriate.
- [ ] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")`, if applicable.
- [ ] UI changes do not introduce regressions when enforcing the current default rules of [Content Security Policy Plugin](https://plugins.jenkins.io/csp/). In particular, new or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content Security Policy (CSP) directives (see [documentation](https://www.jenkins.io/doc/developer/security/csp/)).
- [ ] For dependency updates, there are links to external changelogs and, if possible, full differentials.
- [ ] For new APIs and extension points, there is a link to at least one consumer.

### Desired reviewers

@mention

Before the changes are marked as `ready-for-merge`:

### Maintainer checklist

- [ ] There are at least two (2) approvals for the pull request and no outstanding requests for change.
- [ ] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [ ] Changelog entries in the pull request title and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [ ] Proper changelog labels are set so that the changelog can be generated automatically.
- [ ] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [ ] If it would make sense to backport the change to LTS, be a _Bug_ or _Improvement_, and either the issue or pull request must be labeled as `lts-candidate` to be considered.

### CODE REVIEW

**Review by timja — APPROVED** [review]

**Review by MarkEWaite — APPROVED** [review]
Tested interactively and confirmed that a job within a folder is unaffected by the change and a job in a multibranch Pipeline is affected by the change.  Much appreciated!

This PR is now ready for merge. We will merge it after approximately 24 hours if there is no negative feedback.

/label ready-for-merge

**Review by NotMyFault — APPROVED** [review]

File: core/src/main/java/hudson/model/Build.java [hunk 1]
```diff
@@ -83,7 +83,7 @@
  *
  * @author Kohsuke Kawaguchi
  */
-public abstract class Build<P extends Project<P, B>, B extends Build<P, B>>
+public abstract class   Build<P extends Project<P, B>, B extends Build<P, B>>
```
Comment (jglick) [inline core/src/main/java/hudson/model/Build.java:86]: Why?

Comment (mawinter69) [reply core/src/main/java/hudson/model/Build.java:86]: hmm sorry for that.
Isn't spotless detecting such things? Or checkstyle?

Comment (MarkEWaite) [reply core/src/main/java/hudson/model/Build.java:86]: > Isn't spotless detecting such things? Or checkstyle?

The spotless configuration on Jenkins core is much less rigorous than the spotless configuration for plugins.  It doesn't detect or correct that type of change.

Comment (timja) [reply core/src/main/java/hudson/model/Build.java:86]: (mostly because of all the PRs we have open and the effort to migrate them, do-able of course)
