### PR TITLE
Fix keyboard navigation scrolling in dropdowns

### LINKED ISSUE #26357: Dropdown menu doesn't scroll when navigating with keyboard
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
Jenkins 2.552-SNAPSHOT
OS: Ubuntu 24.04
Java: 21.0.10 - Ubuntu (OpenJDK 64-Bit Server VM)
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Ubuntu 24.04.4 LTS

### Reproduction steps

1. Start Jenkins
2. Goto Manage Jenkins page
3. Click on Manage Jenkins dropdown menu
4. Press arrow down key repeatedly to navigate through items
Attaching video for reference:

https://github.com/user-attachments/assets/486b9e34-92b7-45b6-a4f8-6ec9dcd9a4f8

### Expected Results

Dropdown should scroll automatically to keep the currently selected item visible when navigating with arrow keys.

### Actual Results

The dropdown doesn't scroll. Items beyond the visible area get selected but stay off-screen, so there's no visual feedback on what's selected.

### Anything else?

_No response_

### Are you interested in contributing a fix?

Yes

### PR DESCRIPTION
**Pull request by SalmanDeveloperz**
Fixes jenkinsci/jenkins#26357

#### Before
Arrow key navigation selected items but didn't scroll, making off-screen items invisible.

https://github.com/user-attachments/assets/ff95a1b5-f2bc-4bd1-8ea7-81ff0f2b64e7

#### After
Dropdown scrolls smoothly to center the selected item when navigating with arrow keys.

https://github.com/user-attachments/assets/c294660a-fdd7-4f48-bb7d-cb79391238d1

### Proposed changelog entries

- Fix keyboard navigation scrolling in dropdowns

### Proposed changelog category

/label bug

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [x] The issue, if it exists, is well-described.
- [x] The changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developers, depending on the change) and are in the imperative mood (see [examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)). Fill in the **Proposed upgrade guidelines** section only if there are breaking changes or changes that may require extra steps from users during upgrade.
- [x] There is automated testing or an explanation as to why this change has no tests.
- [x] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadocs, as appropriate.
- [x] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")`, if applicable.
- [x] UI changes do not introduce regressions when enforcing the current default rules of [Content Security Policy Plugin](https://plugins.jenkins.io/csp/). In particular, new or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content Security Policy (CSP) directives (see [documentation](https://www.jenkins.io/doc/developer/security/csp/)).
- [ ] For dependency updates, there are links to external changelogs and, if possible, full differentials.
- [ ] For new APIs and extension points, there is a link to at least one consumer.

### Desired reviewers

@timja 

Before the changes are marked as `ready-for-merge`:

### Maintainer checklist

- [ ] There are at least two (2) approvals for the pull request and no outstanding requests for change.
- [ ] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [ ] Changelog entries in the pull request title and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [ ] Proper changelog labels are set so that the changelog can be generated automatically.
- [ ] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [ ] If it would make sense to backport the change to LTS, be a _Bug_ or _Improvement_, and either the issue or pull request must be labeled as `lts-candidate` to be considered.

### CODE REVIEW

File: src/main/js/util/keyboard.js [hunk 1]
```diff
@@ -82,22 +82,10 @@ export default function makeKeyboardNavigable(
 
 function scrollAndSelect(selectedItem, selectedClass, items) {
   if (selectedItem) {
-    if (!isInViewport(selectedItem)) {
-      selectedItem.scrollIntoView(false);
-    }
+    selectedItem.scrollIntoView({ block: "center", behavior: "smooth" });
```
Comment (timja) [inline src/main/js/util/keyboard.js]: Whilst this does fix the bug (which is the priority) it is scrolling too early and its a bit jumpy.

Could you investigate if the `isInViewport` function could be fixed instead? as I assume that was intended to only scroll when needed. (cc @mawinter69 as the author of that change)

the `block: center` does seem better. When it was anchored to the bottom which is what false does it was good when going down but when going back up it was a bit strange feeling.

Comment (SalmanDeveloperz) [reply src/main/js/util/keyboard.js]: Good point. I tested with `block: 'nearest'` initially, which only scrolls when needed, but it didn't show section headers when wrapping from bottom to top (e.g. selecting "System" didn't show the "Actions" and "System Configuration" header above it).
image

The `isInViewport` function checks if the element is in the browser window, not the dropdown container. Items scrolled out of view in the dropdown still pass the check because they're technically in the window, so scrolling never triggers.

I can fix `isInViewport` to check visibility within the dropdown bounds instead. That would keep the "only scroll when needed" behavior while fixing the bug. Want me to go that route?

Comment (timja) [reply src/main/js/util/keyboard.js]: > I can fix isInViewport to check visibility within the dropdown bounds instead. That would keep the "only scroll when needed" behavior while fixing the bug. Want me to go that route?

Give it a go, would be better if it was less jarring, but if we can't get something nicer at least this works.

Comment (SalmanDeveloperz) [reply src/main/js/util/keyboard.js]: Will update to check dropdown container visibility. Testing now !

Comment (SalmanDeveloperz) [reply src/main/js/util/keyboard.js]: > Could you investigate if the `isInViewport` function could be fixed instead? as I assume that was intended to only scroll when needed. (cc @mawinter69 as the author of that change)
>
Tried fixing `isInViewport` to check dropdown container visibility but ran into issues, the dropdown doesn't have a max-height in the DOM, so it sizes to fit all items and visibility checks always pass.

The `"nearest"` approach scrolls smoothly and only when needed. 
Minor edge case: section headers don't always show when wrapping bottom to top, but navigation works fine.

Video attached.

https://github.com/user-attachments/assets/c99e47b1-fe32-4b91-af48-94231bb3a735

Worth committing or should try something else?

Comment (timja) [reply src/main/js/util/keyboard.js]: yeah lets go for nearest

Comment (SalmanDeveloperz) [reply src/main/js/util/keyboard.js]: Done!

**Review by timja — APPROVED** [review]
Tested locally, this works a lot better.

Yes the headings don't show when you loop back around when scrolling but meh its fine.

Thanks!

If you're looking for another similar issue, while testing this fix I noticed (and reported) https://github.com/jenkinsci/jenkins/issues/26378

**Review by andreahlert — APPROVED** [review]
Tested. LGTM.

**Comment by timja** [comment]
/label ready-for-merge

----

This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

**Review by NotMyFault — APPROVED** [review]
