### PR TITLE
[JENKINS-63343] Validate element types for collections and maps when deserializing XML files

### LINKED ISSUE #12099: [JENKINS-66029] Illegal reflective access by XStream
<p>With the implied labels plugin 0.7 installed on my Jenkins 2.289.1 using the label definitions as described in <a href="https://github.com/MarkEWaite/docker-lfs/blob/557b67944b7b4f37f493eac8e4f2f6a253eb02aa/ref/org.jenkinsci.plugins.impliedlabels.Config.xml#L1" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/MarkEWaite/docker-lfs/blob/557b67944b7b4f37f493eac8e4f2f6a253eb02aa/ref/org.jenkinsci.plugins.impliedlabels.Config.xml#L1</a> , Java 11 reports an illegal access exception during startup.</p>

<p>The stack trace for the illegal access exception is:</p>

<pre>
WARNING: Illegal reflective access by com.thoughtworks.xstream.converters.reflection.FieldDictionary (file:/<span class="code-keyword">var</span>/jenkins_home/war/WEB-INF/lib/xstream-1.4.17.jar) to field java.util.Collections$UnmodifiableCollection.serialVersionUID
at com.thoughtworks.xstream.converters.reflection.FieldDictionary.buildDictionaryEntryForClass(FieldDictionary.java:176)
at com.thoughtworks.xstream.converters.reflection.FieldDictionary.buildMap(FieldDictionary.java:142)
at com.thoughtworks.xstream.converters.reflection.FieldDictionary.fieldOrNull(FieldDictionary.java:115)
at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.getFieldOrNull(PureJavaReflectionProvider.java:197)
at hudson.util.RobustReflectionConverter.fieldDefinedInClass(RobustReflectionConverter.java:434)
at hudson.util.RobustReflectionConverter.doUnmarshal(RobustReflectionConverter.java:296)
at hudson.util.RobustReflectionConverter.unmarshal(RobustReflectionConverter.java:280)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:72)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
at hudson.util.RobustReflectionConverter.unmarshalField(RobustReflectionConverter.java:439)
at hudson.util.RobustReflectionConverter.doUnmarshal(RobustReflectionConverter.java:341)
at hudson.util.RobustReflectionConverter.unmarshal(RobustReflectionConverter.java:280)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:72)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:134)
at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32)
at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1431)
at hudson.util.XStream2.unmarshal(XStream2.java:161)
at hudson.util.XStream2.unmarshal(XStream2.java:132)
at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1411)
at hudson.XmlFile.unmarshal(XmlFile.java:180)
at hudson.XmlFile.unmarshal(XmlFile.java:163)
at org.jenkinsci.plugins.impliedlabels.Config.load(Config.java:211)
at org.jenkinsci.plugins.impliedlabels.Config.<init>(Config.java:80)
at org.jenkinsci.plugins.impliedlabels.ImpliedLabelsPlugin.<clinit>(ImpliedLabelsPlugin.java:33)
at java.base/java.lang.<span class="code-object">Class</span>.newInstance(<span class="code-object">Class</span>.java:584)
at hudson.ClassicPluginStrategy.load(ClassicPluginStrategy.java:378)
at hudson.PluginManager$2$1$1.run(PluginManager.java:551)
at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
</pre>

<p>Issue is reported at this line:</p>

<p><a href="https://github.com/jenkinsci/implied-labels-plugin/blob/777c5e4bf8438dae723d0b31edd0c399899ceb65/src/main/java/org/jenkinsci/plugins/impliedlabels/Config.java#L211" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/implied-labels-plugin/blob/777c5e4bf8438dae723d0b31edd0c399899ceb65/src/main/java/org/jenkinsci/plugins/impliedlabels/Config.java#L211</a></p>

---
<details><summary><i>Originally reported by  <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=markewaite">markewaite</a>, imported from: <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-66029" target="_blank">Illegal reflective access by XStream</a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Minor
<li><b>component(s)</b>: core
<li><b>label(s)</b>: java11
<li><b>resolution</b>: Unresolved
<li><b>votes</b>: 0
<li><b>watchers</b>: 3
<li><b>imported</b>: 2025-11-24
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p>With the implied labels plugin 0.7 installed on my Jenkins 2.289.1 using the label definitions as described in <a href="https://github.com/MarkEWaite/docker-lfs/blob/557b67944b7b4f37f493eac8e4f2f6a253eb02aa/ref/org.jenkinsci.plugins.impliedlabels.Config.xml#L1" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/MarkEWaite/docker-lfs/blob/557b67944b7b4f37f493eac8e4f2f6a253eb02aa/ref/org.jenkinsci.plugins.impliedlabels.Config.xml#L1</a> , Java 11 reports an illegal access exception during startup.</p>

<p>The stack trace for the illegal access exception is:</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">WARNING: Illegal reflective access by com.thoughtworks.xstream.converters.reflection.FieldDictionary (file:/<span class="code-keyword">var</span>/jenkins_home/war/WEB-INF/lib/xstream-1.4.17.jar) to field java.util.Collections$UnmodifiableCollection.serialVersionUID
        at com.thoughtworks.xstream.converters.reflection.FieldDictionary.buildDictionaryEntryForClass(FieldDictionary.java:176)
        at com.thoughtworks.xstream.converters.reflection.FieldDictionary.buildMap(FieldDictionary.java:142)
        at com.thoughtworks.xstream.converters.reflection.FieldDictionary.fieldOrNull(FieldDictionary.java:115)
        at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.getFieldOrNull(PureJavaReflectionProvider.java:197)
        at hudson.util.RobustReflectionConverter.fieldDefinedInClass(RobustReflectionConverter.java:434)
        at hudson.util.RobustReflectionConverter.doUnmarshal(RobustReflectionConverter.java:296)
        at hudson.util.RobustReflectionConverter.unmarshal(RobustReflectionConverter.java:280)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
        at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:72)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
        at hudson.util.RobustReflectionConverter.unmarshalField(RobustReflectionConverter.java:439)
        at hudson.util.RobustReflectionConverter.doUnmarshal(RobustReflectionConverter.java:341)
        at hudson.util.RobustReflectionConverter.unmarshal(RobustReflectionConverter.java:280)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
        at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:72)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:134)
        at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32)
        at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1431)
        at hudson.util.XStream2.unmarshal(XStream2.java:161)
        at hudson.util.XStream2.unmarshal(XStream2.java:132)
        at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1411)
        at hudson.XmlFile.unmarshal(XmlFile.java:180)
        at hudson.XmlFile.unmarshal(XmlFile.java:163)
        at org.jenkinsci.plugins.impliedlabels.Config.load(Config.java:211)
        at org.jenkinsci.plugins.impliedlabels.Config.&lt;init&gt;(Config.java:80)
        at org.jenkinsci.plugins.impliedlabels.ImpliedLabelsPlugin.&lt;clinit&gt;(ImpliedLabelsPlugin.java:33)
        at java.base/java.lang.<span class="code-object">Class</span>.newInstance(<span class="code-object">Class</span>.java:584)
        at hudson.ClassicPluginStrategy.load(ClassicPluginStrategy.java:378)
        at hudson.PluginManager$2$1$1.run(PluginManager.java:551)
        at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
</pre>
</div></div>

<p>Issue is reported at this line:</p>

<p><a href="https://github.com/jenkinsci/implied-labels-plugin/blob/777c5e4bf8438dae723d0b31edd0c399899ceb65/src/main/java/org/jenkinsci/plugins/impliedlabels/Config.java#L211" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/implied-labels-plugin/blob/777c5e4bf8438dae723d0b31edd0c399899ceb65/src/main/java/org/jenkinsci/plugins/impliedlabels/Config.java#L211</a></p></pre>
</details>
</details>
<details><summary><i>environment</i></summary>

```
Jenkins 2.289.1<br/>
Java 11.0.11<br/>
Implied labels plugin 0.7
```
</details>

### PR DESCRIPTION
**Pull request by dwnusbaum**
See [JENKINS-63343](https://issues.jenkins.io/browse/JENKINS-63343). This PR checks all fields being deserialized to see if they will be handled by `RobustCollectionConverter` or `RobustMapConverter`, and if so, it explicitly constructs an instance of the converter specialized to the type of the field in question so that collection elements and map keys and values can be type checked. Any values which do not have the expected type are ignored, and an `OldDataMonitor` warning is logged. 

### Testing done

See new automated tests.

### Proposed changelog entries

- Ignore values with incorrect types when deserializing collections and maps in XML files.

### Proposed upgrade guidelines

N/A

```[tasklist]
### Submitter checklist
- [x] The Jira issue, if it exists, is well-described.
- [x] The changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developers, depending on the change) and are in the imperative mood (see [examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)). Fill in the **Proposed upgrade guidelines** section only if there are breaking changes or changes that may require extra steps from users during upgrade.
- [x] There is automated testing or an explanation as to why this change has no tests.
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadocs, as appropriate.
- [ ] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")`, if applicable.
- [ ] New or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content Security Policy (CSP) directives (see [documentation](https://www.jenkins.io/doc/developer/security/csp/)).
- [ ] For dependency updates, there are links to external changelogs and, if possible, full differentials.
- [ ] For new APIs and extension points, there is a link to at least one consumer.
```

### Desired reviewers

@mention

Before the changes are marked as `ready-for-merge`:

```[tasklist]
### Maintainer checklist
- [x] There are at least two (2) approvals for the pull request and no outstanding requests for change.
- [x] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [x] Changelog entries in the pull request title and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [x] Proper changelog labels are set so that the changelog can be generated automatically.
- [ ] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).
```

### CODE REVIEW

File: core/src/main/java/hudson/util/RobustCollectionConverter.java [hunk 1]
```diff
@@ -52,14 +55,33 @@
...
     }
 
     public RobustCollectionConverter(Mapper mapper, ReflectionProvider reflectionProvider) {
+        this(mapper, reflectionProvider, null);
+    }
+
+    public RobustCollectionConverter(Mapper mapper, ReflectionProvider reflectionProvider, Type collectionType) {
         super(mapper);
         sc = new SerializableConverter(mapper, reflectionProvider, new ClassLoaderReference(null));
+        if (collectionType != null && Collection.class.isAssignableFrom(Types.erasure(collectionType))) {
```
[the remark this answers is not in the document]
Comment (dwnusbaum) [reply core/src/main/java/hudson/util/RobustCollectionConverter.java:78]: Probably, I didn't bother looking into it yet since the code in `RobustReflectionConverter` doesn't really feel right to me.

File: core/src/test/java/hudson/util/RobustCollectionConverterTest.java [hunk 2]
```diff
@@ -173,4 +174,53 @@ private Set<Object> preparePayload() {
...
+                  <numbers>
+                    <int>1</int>
+                    <int>2</int>
+                    <string>oops!</string>
+                    <int>3</int>
+                  </numbers>
+                </hudson.util.RobustCollectionConverterTest_-Numbers>
+                """;
+        var actual = (Numbers) new XStream2().fromXML(xmlContent);
+        assertEquals(expected, actual);
```
[the remark this answers is not in the document]
Comment (dwnusbaum) [reply core/src/test/java/hudson/util/RobustCollectionConverterTest.java:193]: I did not check it, but yes that is the hope.

File: core/src/main/java/hudson/util/RobustReflectionConverter.java [hunk 3]
```diff
@@ -451,6 +451,10 @@ private boolean fieldDefinedInClass(Object result, String attrName) {
 
     protected Object unmarshalField(final UnmarshallingContext context, final Object result, Class type, Field field) {
         Converter converter = mapper.getLocalConverter(field.getDeclaringClass(), field.getName());
+        // TODO: Is there a better way to make something like this work? Does it break any custom converters?
+        if (converter == null && new RobustCollectionConverter(mapper, reflectionProvider).canConvert(type)) {
+            converter = new RobustCollectionConverter(mapper, reflectionProvider, field.getGenericType());
+        }
```
Comment (dwnusbaum) [inline core/src/main/java/hudson/util/RobustReflectionConverter.java:457]: In particular I am wondering about things like [NodeList](https://github.com/jenkinsci/jenkins/blob/2d2adefabdf9edf025a277c95d1fc9d33bbfe14c/core/src/main/java/hudson/slaves/NodeList.java) and [AxisList](https://github.com/jenkinsci/matrix-project-plugin/blob/7ef205d818d6386125e0c042dd9093a7bbe883cd/src/main/java/hudson/matrix/AxisList.java) which extend `ArrayList`. They might be ok because of the exact equality comparisons [here](https://github.com/x-stream/xstream/blob/8472df83122b6b0840fc6d8c7945b5b55c25fb9d/xstream/src/java/com/thoughtworks/xstream/converters/collections/CollectionConverter.java#L64-L74), but I am not sure. I guess also that those classes don't support any of the desired recoverability features in `RobustCollectionConverter`, but that shouldn't be affected by my PR.

Comment (dwnusbaum) [reply core/src/main/java/hudson/util/RobustReflectionConverter.java:457]: I confirmed that `NodeList` is unaffected by this change - its custom converter continues to be used and its deserialization is not robust against invalid values.

Comment (dwnusbaum) [reply core/src/main/java/hudson/util/RobustReflectionConverter.java:457]: Looking at https://github.com/jenkinsci/jenkins/pull/342, I think we only expect `getLocalConverter` to matter for fields that have the `@XStreamConverter` annotation, which seems to be more or less unused based on [this search](https://github.com/search?type=code&q=+owner%3Ajenkinsci+%22%40XStreamConverter%22+-path%3Asrc%2Ftest+-path%3Axstream-distribution), and also none of those annotations are for collections or maps.

File: core/src/main/java/hudson/util/RobustCollectionConverter.java (hunk 1 above)
[the remark this answers is not in the document]
Comment (dwnusbaum) [reply core/src/main/java/hudson/util/RobustCollectionConverter.java:79]: The PR handles maps as of [966f598](https://github.com/jenkinsci/jenkins/pull/9727/commits/966f598d7cec0359aff7694bcd87ff3e10135965).

File: core/src/test/java/hudson/util/RobustCollectionConverterTest.java (hunk 2 above)
[the remark this answers is not in the document]
Comment (dwnusbaum) [reply core/src/test/java/hudson/util/RobustCollectionConverterTest.java]: As of [61db49c](https://github.com/jenkinsci/jenkins/pull/9727/commits/61db49c2e723d223552f799b9206273056a13b3d) the error messages have been improved and the tests log the warnings. Here is an example of the warning for a bad list element:

```
Sep 18, 2024 5:09:31 PM hudson.diagnosis.OldDataMonitor report
WARNING: could not read hudson.util.RobustCollectionConverterTest$Data@2cc3ad05 (and Jenkins did not start up)
com.thoughtworks.xstream.converters.ConversionException: Invalid type for collection element
---- Debugging information ----
message             : Invalid type for collection element
cause-exception     : java.lang.ClassCastException
cause-message       : Cannot cast java.lang.String to java.lang.Integer
path                : /hudson.util.RobustCollectionConverterTest$Data/numbers/string
line number         : 5
-------------------------------
    at hudson.util.RobustCollectionConverter.populateCollection(RobustCollectionConverter.java:120)
    at com.thoughtworks.xstream.converters.collections.CollectionConverter.unmarshal(CollectionConverter.java:81)
    at hudson.util.RobustCollectionConverter.unmarshal(RobustCollectionConverter.java:101)
    at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:74)
    at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:72)
    at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:68)
    at hudson.util.RobustReflectionConverter.unmarshalField(RobustReflectionConverter.java:461)
    at hudson.util.RobustReflectionConverter.doUnmarshal(RobustReflectionConverter.java:350)
    at hudson.util.RobustReflectionConverter.unmarshal(RobustReflectionConverter.java:289)
    at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:74)
    at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:72)
    at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:68)
    at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:52)
    at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:136)
    at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32)
    at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1464)
    at hudson.util.XStream2.unmarshal(XStream2.java:230)
    at hudson.util.XStream2.unmarshal(XStream2.java:201)
    at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1441)
    at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1321)
    at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1312)
    at hudson.util.RobustCollectionConverterTest.checkElementTypes(RobustCollectionConverterTest.java:207)
    ... surefire ...
    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
Caused by: java.lang.ClassCastException: Cannot cast java.lang.String to java.lang.Integer
    at java.base/java.lang.Class.cast(Class.java:3889)
    at hudson.util.RobustCollectionConverter.populateCollection(RobustCollectionConverter.java:114)
    ... 65 more
```

Here is an example for a bad map value:

```

WARNING: could not read hudson.util.RobustMapConverterTest$Data@2a5b3fee (and Jenkins did not start up)
com.thoughtworks.xstream.converters.ConversionException: Invalid type for map entry key/value
---- Debugging information ----
message             : Invalid type for map entry key/value
cause-exception     : java.lang.ClassCastException
cause-message       : Cannot cast java.lang.Integer to java.lang.String
path                : /hudson.util.RobustMapConverterTest$Data/map/entry[2]/int
line number         : 9
-------------------------------
    at hudson.util.RobustMapConverter.read(RobustMapConverter.java:114)
    at hudson.util.RobustMapConverter.putCurrentEntryIntoMap(RobustMapConverter.java:81)
    at com.thoughtworks.xstream.converters.collections.MapConverter.populateMap(MapConverter.java:99)
    at com.thoughtworks.xstream.converters.collections.MapConverter.populateMap(MapConverter.java:93)
    at com.thoughtworks.xstream.converters.collections.MapConverter.unmarshal(MapConverter.java:88)
    at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:74)
    at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:72)
    at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:68)
    at hudson.util.RobustReflectionConverter.unmarshalField(RobustReflectionConverter.java:461)
    at hudson.util.RobustReflectionConverter.doUnmarshal(RobustReflectionConverter.java:350)
    at hudson.util.RobustReflectionConverter.unmarshal(RobustReflectionConverter.java:289)
    at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:74)
    at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:72)
    at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:68)
    at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:52)
    at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:136)
    at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32)
    at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1464)
    at hudson.util.XStream2.unmarshal(XStream2.java:230)
    at hudson.util.XStream2.unmarshal(XStream2.java:201)
    at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1441)
    at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1321)
    at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1312)
    at hudson.util.RobustMapConverterTest.robustAgainstInvalidValueType(RobustMapConverterTest.java:244)
    ... surefire ...
    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
Caused by: java.lang.ClassCastException: Cannot cast java.lang.Integer to java.lang.String
    at java.base/java.lang.Class.cast(Class.java:3889)
    at hudson.util.RobustMapConverter.read(RobustMapConverter.java:110)
    ... 67 more

```

File: core/src/main/java/hudson/util/RobustReflectionConverter.java [hunk 4]
```diff
@@ -451,6 +451,13 @@ private boolean fieldDefinedInClass(Object result, String attrName) {
 
     protected Object unmarshalField(final UnmarshallingContext context, final Object result, Class type, Field field) {
         Converter converter = mapper.getLocalConverter(field.getDeclaringClass(), field.getName());
+        if (converter == null) {
+            if (new RobustCollectionConverter(mapper, reflectionProvider).canConvert(type)) {
```
Comment (dwnusbaum) [inline core/src/main/java/hudson/util/RobustReflectionConverter.java:455]: It's a bit awkward to recreate this for every single field being unmarshalled, should we keep an instance as a local field just for these `canConvert` calls?

File: core/src/main/java/hudson/util/RobustReflectionConverter.java [hunk 5]
```diff
@@ -451,6 +451,13 @@ private boolean fieldDefinedInClass(Object result, String attrName) {
 
     protected Object unmarshalField(final UnmarshallingContext context, final Object result, Class type, Field field) {
         Converter converter = mapper.getLocalConverter(field.getDeclaringClass(), field.getName());
+        if (converter == null) {
```
Comment (dwnusbaum) [inline core/src/main/java/hudson/util/RobustReflectionConverter.java:454]: See https://github.com/jenkinsci/jenkins/pull/9727#discussion_r1761868912 for discussion about cases where `converter` is not null. In short, I don't think we care. 

I am not sure though whether this method covers all of the cases we care about. It seems like we may need similar changes related to "implicit collections". I will look into that a bit.

Comment (dwnusbaum) [reply core/src/main/java/hudson/util/RobustReflectionConverter.java:454]: Specifically, prior to this line, I think we should look up the field and then add code comparable to what we added to `RobustCollectionConverter` to validate the value type: https://github.com/jenkinsci/jenkins/blob/1836bd6ef4cece1e261dcce22f57dab3cc898c7f/core/src/main/java/hudson/util/RobustReflectionConverter.java#L477

Needs to be investigated with a test case.

Comment (dwnusbaum) [reply core/src/main/java/hudson/util/RobustReflectionConverter.java:457]: I looked into the cases related to implicit collections today. My understanding is that you need to explicitly call `addImplicitArray`, `addImplicitCollection`, or `addImplicitMap` for the relevant code to matter, which is not very common, see [here](https://github.com/search?type=code&q=+owner%3Ajenkinsci+addImplicit+-path%3Asrc%2Ftest+-repo%3Ajenkinsci%2Fjs-libs+-repo%3Ajenkinsci%2Fgroovy+-repo%3Ajenkinsci%2Fxstream+-repo%3Ajenkinsci%2Fxstream-fork) (there are also a few usages in CloudBees plugins). The overloads where you specify the item type already avoid JENKINS-63343 because of `getFieldNameForItemTypeAndName` [here](https://github.com/jenkinsci/jenkins/blob/1836bd6ef4cece1e261dcce22f57dab3cc898c7f/core/src/main/java/hudson/util/RobustReflectionConverter.java#L458) which uses `context.getRequiredType()` leading to invalid elements being silently ignored. The overloads for arrays and maps seem to not actually work at all due to [this check](https://github.com/jenkinsci/jenkins/blob/1836bgd6ef4cece1e261dcce22f57dab3cc898c7f/core/src/main/java/hudson/util/RobustReflectionConverter.java#L466-L469) (which leaves me somewhat confused about https://github.com/jenkinsci/jenkins/pull/2621, but perhaps my testing did not cover all cases).

So, I think we do not really care much about implicit collections, but [09ca355](https://github.com/jenkinsci/jenkins/pull/9727/commits/09ca355d0eaa8212129dab7aeb0acd1d16e9fcf5) should handle them too.

File: core/src/main/java/hudson/util/RobustCollectionConverter.java [hunk 6]
```diff
@@ -52,14 +56,33 @@
...
+            var baseType = Types.getBaseClass(collectionType, Collection.class);
+            var typeArg = Types.getTypeArgument(baseType, 0, Object.class);
```
Comment (jglick) [inline core/src/main/java/hudson/util/RobustCollectionConverter.java:81]: What happens here if the field is using a rawtype?

File: core/src/main/java/hudson/util/RobustCollectionConverter.java [hunk 7]
```diff
@@ -85,9 +108,19 @@ protected void populateCollection(HierarchicalStreamReader reader, Unmarshalling
...
-                XStream2SecurityUtils.checkForCollectionDoSAttack(context, nanoNow);
+                try {
+                    if (elementType != null) {
+                        // When possible, disallow invalid elements.
+                        elementType.cast(item);
+                    }
+                    long nanoNow = System.nanoTime();
+                    collection.add(item);
+                    XStream2SecurityUtils.checkForCollectionDoSAttack(context, nanoNow);
+                } catch (ClassCastException e) {
```
Comment (jglick) [inline core/src/main/java/hudson/util/RobustCollectionConverter.java:119]: Can this be thrown from something after the `Class.cast`? If not, it would be better to use `isInstance` without a `try`-`catch` block.

File: core/src/main/java/hudson/util/RobustMapConverter.java [hunk 8]
```diff
@@ -42,13 +45,40 @@
 final class RobustMapConverter extends MapConverter {
     private static final Object ERROR = new Object();
 
+    /**
+     * When available, this field holds the declared type of the keys of the map being deserialized.
+     * This is used to ensure that deserialized keys have the expected type.
+     */
+    // See note above RobustCollectionConverter.elementType for limitations regarding non-concrete parameterized types.
```
Comment (jglick) [inline core/src/main/java/hudson/util/RobustMapConverter.java:52]: Does Javadoc work when you have an intervening non-doc comment?

File: core/src/main/java/hudson/util/RobustMapConverter.java [hunk 9]
```diff
@@ -42,13 +45,40 @@
...
+        this(mapper, null);
+    }
+
+    RobustMapConverter(Mapper mapper, Type mapType) {
         super(mapper);
+        if (mapType != null && Map.class.isAssignableFrom(Types.erasure(mapType))) {
+            var baseType = Types.getBaseClass(mapType, Map.class);
+            var keyTypeArg = Types.getTypeArgument(baseType, 0, Object.class);
+            this.keyType = Types.erasure(keyTypeArg);
+            var valueTypeArg = Types.getTypeArgument(baseType, 1, Object.class);
```
Comment (jglick) [inline core/src/main/java/hudson/util/RobustMapConverter.java:71]: ditto, check rawtype behavior

File: core/src/main/java/hudson/util/RobustMapConverter.java [hunk 10]
```diff
@@ -73,7 +103,19 @@ private Object read(HierarchicalStreamReader reader, UnmarshallingContext contex
...
         try {
-            return readBareItem(reader, context, map);
+            var object = readBareItem(reader, context, map);
+            try {
+                if (expectedType != null) {
+                    // When possible, disallow invalid keys and values.
+                    expectedType.cast(object);
+                }
+                return object;
+            } catch (ClassCastException e) {
```
Comment (jglick) [inline core/src/main/java/hudson/util/RobustMapConverter.java:113]: This definitely looks like it should be using https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/Class.html#isInstance(java.lang.Object)

File: core/src/main/java/hudson/util/RobustReflectionConverter.java [hunk 11]
```diff
@@ -324,7 +326,8 @@ public Object doUnmarshal(final Object result, final HierarchicalStreamReader re
             }
         }
 
-        Map implicitCollectionsForCurrentObject = null;
+        Map<String, Collection> implicitCollectionsForCurrentObject = new HashMap<>();
```
Comment (jglick) [inline core/src/main/java/hudson/util/RobustReflectionConverter.java:329]:
```suggestion
        Map<String, Collection<Object>> implicitCollectionsForCurrentObject = new HashMap<>();
```
?

File: core/src/main/java/hudson/util/RobustReflectionConverter.java [hunk 12]
```diff
@@ -451,18 +454,23 @@ private boolean fieldDefinedInClass(Object result, String attrName) {
...
+                converter = new RobustCollectionConverter(mapper, reflectionProvider, field.getGenericType());
+            } else if (new RobustMapConverter(mapper).canConvert(type)) {
+                converter = new RobustMapConverter(mapper, field.getGenericType());
+            }
+        }
         return context.convertAnother(result, type, converter);
     }
 
-    private Map writeValueToImplicitCollection(UnmarshallingContext context, Object value, Map implicitCollections, Object result, String itemFieldName) {
+    private void writeValueToImplicitCollection(HierarchicalStreamReader reader, UnmarshallingContext context, Object value, Map<String, Collection> implicitCollections, Map<String, Class<?>> implicitCollectionElementTypes, Object result, String itemFieldName) {
```
Comment (jglick) [inline core/src/main/java/hudson/util/RobustReflectionConverter.java:467]: same,
```suggestion
    private void writeValueToImplicitCollection(HierarchicalStreamReader reader, UnmarshallingContext context, Object value, Map<String, Collection<Object>> implicitCollections, Map<String, Class<?>> implicitCollectionElementTypes, Object result, String itemFieldName) {
```
perhaps

File: core/src/main/java/hudson/util/RobustReflectionConverter.java [hunk 13]
```diff
@@ -473,10 +481,23 @@ private Map writeValueToImplicitCollection(UnmarshallingContext context, Object
...
                 implicitCollections.put(fieldName, collection);
+                Type fieldGenericType = field.getGenericType();
+                Type elementGenericType = Types.getTypeArgument(Types.getBaseClass(fieldGenericType, Collection.class), 0, Object.class);
+                Class<?> elementType = Types.erasure(elementGenericType);
+                implicitCollectionElementTypes.put(fieldName, elementType);
+            }
+            Class<?> elementType = implicitCollectionElementTypes.getOrDefault(fieldName, Object.class);
+            try {
+                elementType.cast(value);
+            } catch (ClassCastException e) {
```
Comment (jglick) [inline core/src/main/java/hudson/util/RobustReflectionConverter.java:492]: `isInstance`

**Review by jglick — APPROVED** [review]
Some minor comments, but generally looks good to the extent I understand it; I definitely do not follow all the subtleties about XStream behavior.

File: core/src/main/java/hudson/util/RobustCollectionConverter.java (hunk 6 above)
Comment (dwnusbaum) [reply core/src/main/java/hudson/util/RobustCollectionConverter.java:81]: Yes good point, I will add a test case for rawtypes.

File: core/src/main/java/hudson/util/RobustMapConverter.java (hunk 8 above)
Comment (dwnusbaum) [reply core/src/main/java/hudson/util/RobustMapConverter.java:52]: As far as I know, yes, for example see https://github.com/openjdk/jdk/blob/2669e22b76c99c1e41a324099154b561e0433b56/src/java.base/share/classes/java/util/HashMap.java#L412-L421. I thought I had seen this pattern used more often in the JDK codebase for implementation notes but that was all I could find in a quick look and it seems to be more typical to use separate block comments. I can adjust the layout.

File: core/src/main/java/hudson/util/RobustMapConverter.java (hunk 10 above)
Comment (dwnusbaum) [reply core/src/main/java/hudson/util/RobustMapConverter.java:113]: Originally this was to be able to throw the `ClassCastException` directly, but yes, now that an explicit `ConversionException` is needed to record contextual information anyway, this can probably be simplified.

File: core/src/main/java/hudson/util/RobustCollectionConverter.java (hunk 6 above)
Comment (dwnusbaum) [reply core/src/main/java/hudson/util/RobustCollectionConverter.java:81]: If we were using `Types.getTypeArgument(Type, int)`, rawtypes would cause an `IllegalArgumentException`. With `Types.getTypeArgument(Type, int, Type)` the default value just gets used instead. I'll still add test cases though.

File: core/src/main/java/hudson/util/RobustReflectionConverter.java (hunk 11 above)
Comment (dwnusbaum) [reply core/src/main/java/hudson/util/RobustReflectionConverter.java]: [c1af611](https://github.com/jenkinsci/jenkins/pull/9727/commits/c1af6116898d3b912ebce9fd24fc7ce989b1fbf9)

File: core/src/main/java/hudson/util/RobustReflectionConverter.java (hunk 12 above)
Comment (dwnusbaum) [reply core/src/main/java/hudson/util/RobustReflectionConverter.java]: [c1af611](https://github.com/jenkinsci/jenkins/pull/9727/commits/c1af6116898d3b912ebce9fd24fc7ce989b1fbf9)

File: core/src/main/java/hudson/util/RobustCollectionConverter.java (hunk 7 above)
Comment (dwnusbaum) [reply core/src/main/java/hudson/util/RobustCollectionConverter.java]: Adjusted in [df2ac81](https://github.com/jenkinsci/jenkins/pull/9727/commits/df2ac81257510f5f0ac715d2bf5036b20b2ffaf7).

File: core/src/main/java/hudson/util/RobustMapConverter.java (hunk 10 above)
Comment (dwnusbaum) [reply core/src/main/java/hudson/util/RobustMapConverter.java]: [df2ac81](https://github.com/jenkinsci/jenkins/pull/9727/commits/df2ac81257510f5f0ac715d2bf5036b20b2ffaf7)

File: core/src/main/java/hudson/util/RobustReflectionConverter.java (hunk 13 above)
Comment (dwnusbaum) [reply core/src/main/java/hudson/util/RobustReflectionConverter.java]: [df2ac81](https://github.com/jenkinsci/jenkins/pull/9727/commits/df2ac81257510f5f0ac715d2bf5036b20b2ffaf7)

File: core/src/main/java/hudson/util/RobustCollectionConverter.java (hunk 6 above)
Comment (dwnusbaum) [reply core/src/main/java/hudson/util/RobustCollectionConverter.java:87]: Tests added in [312e51c](https://github.com/jenkinsci/jenkins/pull/9727/commits/312e51c9464c8f6d2342a7a0a7983cab2f00b5b9).

File: core/src/main/java/hudson/util/RobustMapConverter.java (hunk 9 above)
Comment (dwnusbaum) [reply core/src/main/java/hudson/util/RobustMapConverter.java:79]: [312e51c](https://github.com/jenkinsci/jenkins/pull/9727/commits/312e51c9464c8f6d2342a7a0a7983cab2f00b5b9)

File: core/src/main/java/hudson/util/RobustMapConverter.java (hunk 8 above)
Comment (dwnusbaum) [reply core/src/main/java/hudson/util/RobustMapConverter.java]: I adjusted things in [801c3e7](https://github.com/jenkinsci/jenkins/pull/9727/commits/801c3e72529775b34cbc77267cfc0ad604cd5bfc).

**Review by jglick — APPROVED** [review]

**Review by jgreffe — APPROVED** [review]

**Comment by dwnusbaum** [comment]
/label ready-for-merge

----

This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!
