### PR TITLE
[JENKINS-76249] Fix form submission when a dropdown changes and the back end response is slow

### LINKED ISSUE #16833: [JENKINS-76249] form submission data is occasionally garbage
<p>In some (as yet unexplained situations) the json form data when adding credentials is garbage.</p>

<h2><a name="StepstoReproduce"></a>Steps to Reproduce</h2>

<ul>
	<li>clone the ATH</li>
	<li>checkout <a href="https://github.com/jenkinsci/acceptance-test-harness/pull/2221/commits/e18af6bd2825976317b16d594eceb5f7a1f5e3b3-" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/acceptance-test-harness/pull/2221/commits/e18af6bd2825976317b16d594eceb5f7a1f5e3b3-</a> (reproduced on master <tt>a4614ed07301ae1b33582b780cca41ad90f111b2</tt>)</li>
	<li>configure your ATH env</li>
	<li>set INTERACTIVE MODE (<tt>export INTERACTIVE=true</tt>)</li>
	<li><tt>mvn clean test -Dtest=SshSlavesPluginTest#newAgent</tt></li>
</ul>

<h2><a name="ExpectedResults"></a>Expected Results</h2>

<ul>
	<li>test passes reliably</li>
</ul>

<h2><a name="ActualResults"></a>Actual Results</h2>

<p>in some cases the test fails as the submitted json is broken,</p>

<p>e.g. </p>

```
------geckoformboundarydcb5b5e50fbcbf4c6b8b778cf6b754f6
Content-Disposition: form-data; name="json"

{"domain":"_","":["1",""],"credentials":{"scope":["GLOBAL","GLOBAL"],"username":["user1",""],"usernameSecret":[false,false],"password":"","$redact":["password","passphrase"],"id":["",""],"description":["Ssh key",""],"privateKeySource":{"value":"0","privateKey":"1212122112","$redact":"privateKey","stapler-class":"com.cloudbees.jenkins.plugins.sshcredentials.impl.BasicSSHUserPrivateKey$DirectEntryPrivateKeySource","$class":"com.cloudbees.jenkins.plugins.sshcredentials.impl.BasicSSHUserPrivateKey$DirectEntryPrivateKeySource"},"passphrase":"","stapler-class":"com.cloudbees.jenkins.plugins.sshcredentials.impl.BasicSSHUserPrivateKey","$class":"com.cloudbees.jenkins.plugins.sshcredentials.impl.BasicSSHUserPrivateKey"},"Jenkins-Crumb":"5f57c3863f722e8911937f70b05c7f385376d795b2d5b004eec8e4a8ae32e50d"}
------geckoformboundarydcb5b5e50fbcbf4c6b8b778cf6b754f6--

```

<p>Note that the values of many paramters (like scope) are doubled up.</p>

<p>The following error is shown in the Jenkins logs</p>

```
2025-10-28 21:15:25.173+0000 [id=78]	WARNING	c.c.p.c.CredentialsSelectHelper$WrappedCredentialsStore#doAddCredentials: Failed to create Credentials
org.kohsuke.stapler.WrongTypeException: Got type array but no lister class found for type class com.cloudbees.plugins.credentials.CredentialsScope
	at org.kohsuke.stapler.RequestImpl$TypePair.convertJSON(RequestImpl.java:917)
Caused: java.lang.IllegalArgumentException: Failed to convert the scope parameter of the constructor public com.cloudbees.jenkins.plugins.sshcredentials.impl.BasicSSHUserPrivateKey(com.cloudbees.plugins.credentials.CredentialsScope,java.lang.String,java.lang.String,com.cloudbees.jenkins.plugins.sshcredentials.impl.BasicSSHUserPrivateKey$PrivateKeySource,java.lang.String,java.lang.String)
	at org.kohsuke.stapler.RequestImpl.instantiate(RequestImpl.java:1010)
	at org.kohsuke.stapler.RequestImpl$TypePair.convertJSON(RequestImpl.java:866)
Caused: java.lang.IllegalArgumentException: Failed to instantiate class com.cloudbees.jenkins.plugins.sshcredentials.impl.BasicSSHUserPrivateKey from {"scope":["GLOBAL","GLOBAL"],"username":["user1",""],"usernameSecret":[false,false],"password":"[value redacted]","$redact":["password","passphrase"],"id":["",""],"description":["Ssh key",""],"privateKeySource":{"value":"0","privateKey":"[value redacted]","$redact":"privateKey","stapler-class":"com.cloudbees.jenkins.plugins.sshcredentials.impl.BasicSSHUserPrivateKey$DirectEntryPrivateKeySource","$class":"com.cloudbees.jenkins.plugins.sshcredentials.impl.BasicSSHUserPrivateKey$DirectEntryPrivateKeySource"},"passphrase":"[value redacted]","stapler-class":"com.cloudbees.jenkins.plugins.sshcredentials.impl.BasicSSHUserPrivateKey","$class":"com.cloudbees.jenkins.plugins.sshcredentials.impl.BasicSSHUserPrivateKey"}
	at org.kohsuke.stapler.RequestImpl$TypePair.convertJSON(RequestImpl.java:870)
	at org.kohsuke.stapler.RequestImpl.bindJSON(RequestImpl.java:633)
	at org.kohsuke.stapler.RequestImpl.bindJSON(RequestImpl.java:628)
	at hudson.model.Descriptor.bindJSON(Descriptor.java:662)
	at hudson.model.Descriptor.newInstanceImpl(Descriptor.java:620)
Caused: java.lang.LinkageError: Failed to instantiate class com.cloudbees.jenkins.plugins.sshcredentials.impl.BasicSSHUserPrivateKey from {"scope":["GLOBAL","GLOBAL"],"username":["user1",""],"usernameSecret":[false,false],"password":"[value redacted]","$redact":["password","passphrase"],"id":["",""],"description":["Ssh key",""],"privateKeySource":{"value":"0","privateKey":"[value redacted]","$redact":"privateKey","stapler-class":"com.cloudbees.jenkins.plugins.sshcredentials.impl.BasicSSHUserPrivateKey$DirectEntryPrivateKeySource","$class":"com.cloudbees.jenkins.plugins.sshcredentials.impl.BasicSSHUserPrivateKey$DirectEntryPrivateKeySource"},"passphrase":"[value redacted]","stapler-class":"com.cloudbees.jenkins.plugins.sshcredentials.impl.BasicSSHUserPrivateKey","$class":"com.cloudbees.jenkins.plugins.sshcredentials.impl.BasicSSHUserPrivateKey"}
	at hudson.model.Descriptor.newInstanceImpl(Descriptor.java:626)
	at hudson.model.Descriptor.newInstance(Descriptor.java:594)
	at hudson.model.Descriptor$NewInstanceBindInterceptor.instantiate(Descriptor.java:709)
	at org.kohsuke.stapler.RequestImpl.instantiate(RequestImpl.java:980)
	at org.kohsuke.stapler.RequestImpl$TypePair.convertJSON(RequestImpl.java:866)
	at org.kohsuke.stapler.RequestImpl.bindJSON(RequestImpl.java:633)
	at org.kohsuke.stapler.RequestImpl.bindJSON(RequestImpl.java:628)
	at hudson.model.Descriptor.bindJSON(Descriptor.java:662)
	at hudson.model.Descriptor.bindJSON(Descriptor.java:637)
	at PluginClassLoader for credentials//com.cloudbees.plugins.credentials.CredentialsSelectHelper$WrappedCredentialsStore.doAddCredentials(CredentialsSelectHelper.java:609)

```

<p>Whilst there is currently no HAR to show this faulty submission, you can start the devtools and enable HAR recording once the test has started (and hope you are lucky that you catch the failure!)</p>

<p>Seems to fail about 1 in 10 for me - failed in the ATH job which reruns failed tests twice.</p>

<p><a href="https://github.com/jenkinsci/acceptance-test-harness/pull/2221/checks?check_run_id=53913818869" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/acceptance-test-harness/pull/2221/checks?check_run_id=53913818869</a></p>

---
<details><summary><i>Originally reported by  <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=teilo">teilo</a>, imported from: <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-76249" target="_blank">form submission data is occasionally garbage </a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Major
<li><b>component(s)</b>: core, credentials-plugin, ssh-credentials-plugin
<li><b>label(s)</b>: form-data
<li><b>resolution</b>: Unresolved
<li><b>votes</b>: 0
<li><b>watchers</b>: 1
<li><b>imported</b>: 2025-11-24
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p>In some (as yet unexplained situations) the json form data when adding credentials is garbage.</p>

<h2><a name="StepstoReproduce"></a>Steps to Reproduce</h2>

<ul>
	<li>clone the ATH</li>
	<li>-checkout <a href="https://github.com/jenkinsci/acceptance-test-harness/pull/2221/commits/e18af6bd2825976317b16d594eceb5f7a1f5e3b3-" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/acceptance-test-harness/pull/2221/commits/e18af6bd2825976317b16d594eceb5f7a1f5e3b3-</a> (reproduced on master <tt>a4614ed07301ae1b33582b780cca41ad90f111b2</tt>)</li>
	<li>configure your ATH env</li>
	<li>set INTERACTIVE MODE (<tt>export INTERACTIVE=true</tt>)</li>
	<li><tt>mvn clean test -Dtest=SshSlavesPluginTest#newAgent</tt></li>
</ul>

<h2><a name="ExpectedResults"></a>Expected Results</h2>

<ul>
	<li>test passes reliably</li>
</ul>

<h2><a name="ActualResults"></a>Actual Results</h2>

<p>in some cases the test fails as the submitted json is broken,</p>

<p>e.g. </p>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>------geckoformboundarydcb5b5e50fbcbf4c6b8b778cf6b754f6
Content-Disposition: form-data; name="json"

{"domain":"_","":["1",""],"credentials":{"scope":["GLOBAL","GLOBAL"],"username":["user1",""],"usernameSecret":[false,false],"password":"","$redact":["password","passphrase"],"id":["",""],"description":["Ssh key",""],"privateKeySource":{"value":"0","privateKey":"1212122112","$redact":"privateKey","stapler-class":"com.cloudbees.jenkins.plugins.sshcredentials.impl.BasicSSHUserPrivateKey$DirectEntryPrivateKeySource","$class":"com.cloudbees.jenkins.plugins.sshcredentials.impl.BasicSSHUserPrivateKey$DirectEntryPrivateKeySource"},"passphrase":"","stapler-class":"com.cloudbees.jenkins.plugins.sshcredentials.impl.BasicSSHUserPrivateKey","$class":"com.cloudbees.jenkins.plugins.sshcredentials.impl.BasicSSHUserPrivateKey"},"Jenkins-Crumb":"5f57c3863f722e8911937f70b05c7f385376d795b2d5b004eec8e4a8ae32e50d"}
------geckoformboundarydcb5b5e50fbcbf4c6b8b778cf6b754f6--
</pre>
</div></div>

<p>Note that the values of many paramters (like scope) are doubled up.</p>

<p>The following error is shown in the Jenkins logs</p>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>2025-10-28 21:15:25.173+0000 [id=78]	WARNING	c.c.p.c.CredentialsSelectHelper$WrappedCredentialsStore#doAddCredentials: Failed to create Credentials
org.kohsuke.stapler.WrongTypeException: Got type array but no lister class found for type class com.cloudbees.plugins.credentials.CredentialsScope
	at org.kohsuke.stapler.RequestImpl$TypePair.convertJSON(RequestImpl.java:917)
Caused: java.lang.IllegalArgumentException: Failed to convert the scope parameter of the constructor public com.cloudbees.jenkins.plugins.sshcredentials.impl.BasicSSHUserPrivateKey(com.cloudbees.plugins.credentials.CredentialsScope,java.lang.String,java.lang.String,com.cloudbees.jenkins.plugins.sshcredentials.impl.BasicSSHUserPrivateKey$PrivateKeySource,java.lang.String,java.lang.String)
	at org.kohsuke.stapler.RequestImpl.instantiate(RequestImpl.java:1010)
	at org.kohsuke.stapler.RequestImpl$TypePair.convertJSON(RequestImpl.java:866)
Caused: java.lang.IllegalArgumentException: Failed to instantiate class com.cloudbees.jenkins.plugins.sshcredentials.impl.BasicSSHUserPrivateKey from {"scope":["GLOBAL","GLOBAL"],"username":["user1",""],"usernameSecret":[false,false],"password":"[value redacted]","$redact":["password","passphrase"],"id":["",""],"description":["Ssh key",""],"privateKeySource":{"value":"0","privateKey":"[value redacted]","$redact":"privateKey","stapler-class":"com.cloudbees.jenkins.plugins.sshcredentials.impl.BasicSSHUserPrivateKey$DirectEntryPrivateKeySource","$class":"com.cloudbees.jenkins.plugins.sshcredentials.impl.BasicSSHUserPrivateKey$DirectEntryPrivateKeySource"},"passphrase":"[value redacted]","stapler-class":"com.cloudbees.jenkins.plugins.sshcredentials.impl.BasicSSHUserPrivateKey","$class":"com.cloudbees.jenkins.plugins.sshcredentials.impl.BasicSSHUserPrivateKey"}
	at org.kohsuke.stapler.RequestImpl$TypePair.convertJSON(RequestImpl.java:870)
	at org.kohsuke.stapler.RequestImpl.bindJSON(RequestImpl.java:633)
	at org.kohsuke.stapler.RequestImpl.bindJSON(RequestImpl.java:628)
	at hudson.model.Descriptor.bindJSON(Descriptor.java:662)
	at hudson.model.Descriptor.newInstanceImpl(Descriptor.java:620)
Caused: java.lang.LinkageError: Failed to instantiate class com.cloudbees.jenkins.plugins.sshcredentials.impl.BasicSSHUserPrivateKey from {"scope":["GLOBAL","GLOBAL"],"username":["user1",""],"usernameSecret":[false,false],"password":"[value redacted]","$redact":["password","passphrase"],"id":["",""],"description":["Ssh key",""],"privateKeySource":{"value":"0","privateKey":"[value redacted]","$redact":"privateKey","stapler-class":"com.cloudbees.jenkins.plugins.sshcredentials.impl.BasicSSHUserPrivateKey$DirectEntryPrivateKeySource","$class":"com.cloudbees.jenkins.plugins.sshcredentials.impl.BasicSSHUserPrivateKey$DirectEntryPrivateKeySource"},"passphrase":"[value redacted]","stapler-class":"com.cloudbees.jenkins.plugins.sshcredentials.impl.BasicSSHUserPrivateKey","$class":"com.cloudbees.jenkins.plugins.sshcredentials.impl.BasicSSHUserPrivateKey"}
	at hudson.model.Descriptor.newInstanceImpl(Descriptor.java:626)
	at hudson.model.Descriptor.newInstance(Descriptor.java:594)
	at hudson.model.Descriptor$NewInstanceBindInterceptor.instantiate(Descriptor.java:709)
	at org.kohsuke.stapler.RequestImpl.instantiate(RequestImpl.java:980)
	at org.kohsuke.stapler.RequestImpl$TypePair.convertJSON(RequestImpl.java:866)
	at org.kohsuke.stapler.RequestImpl.bindJSON(RequestImpl.java:633)
	at org.kohsuke.stapler.RequestImpl.bindJSON(RequestImpl.java:628)
	at hudson.model.Descriptor.bindJSON(Descriptor.java:662)
	at hudson.model.Descriptor.bindJSON(Descriptor.java:637)
	at PluginClassLoader for credentials//com.cloudbees.plugins.credentials.CredentialsSelectHelper$WrappedCredentialsStore.doAddCredentials(CredentialsSelectHelper.java:609)
</pre>
</div></div>

<p>Whilst there is currently no HAR to show this faulty submission, you can start the devtools and enable HAR recording once the test has started (and hope you are lucky that you catch the failure!)</p>

<p>Seems to fail about 1 in 10 for me - failed in the ATH job which reruns failed tests twice.</p>

<p><a href="https://github.com/jenkinsci/acceptance-test-harness/pull/2221/checks?check_run_id=53913818869" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/acceptance-test-harness/pull/2221/checks?check_run_id=53913818869</a></p></pre>
</details>
</details>
<details><summary><i>environment</i></summary>

```
Jenkins 2.528.1<br/>
Java 17<br/>
Firefox<br/>
ATH
```
</details>

### PR DESCRIPTION
**Pull request by jtnord**
calling `renderOnDemand` can cause the DOM to be manipulated aynchronously due to function calls going to the Jenkins server (e.g. `stapler/bound/xxx/render`).  When this occurs if there is a subsequent change to the dropdown selection before this completes, when the HTML is finally obtained from Jenkins it is inserted into the DOM, but it is inserted as if it is still the selected option (ie it is not disable for the form).

`renderOnDemand` takes a callback function that will be called when the DOM manipulation is complete, however the `updateDropDownList` did not pass any function.

We now pass a function that manipulates the just added HTML if the selected item is in fact no longer selected.

Fixes #16833

### Testing done

*  Commented out the fix https://github.com/jenkinsci/jenkins/blob/03eaf02824164bc6b187127003dde5d9afd893e9/war/src/main/webapp/scripts/hudson-behavior.js#L1719-L1721
*  Ran `mvn test -Dtest=SshSlavesPluginTest#newAgent` in a loop.

Observed that the test failed ~ 1 time in 10 and that the newly added console log (`**** renderOnDemandCallback, selection no longer valid, form submission would have been corrupted`) always appeared when the test would fail (and very rarely appeared otherwise)

* Reintroduced the fix
* Ran  `mvn test -Dtest=SshSlavesPluginTest#newAgent` again.

Observed I still see the newly introduced console log ~ 1 time in 10m but the test did not fail in > 800 runs.

### Proposed changelog entries

- Submitting a form would in rare cases, lead to an error (`Got type array but no lister class found for type...`)

### Proposed changelog category

/label <update-this-with-category>

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] The issue, if it exists, is well-described.
- [ ] The changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developers, depending on the change) and are in the imperative mood (see [examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)). Fill in the **Proposed upgrade guidelines** section only if there are breaking changes or changes that may require extra steps from users during upgrade.
- [ ] There is automated testing or an explanation as to why this change has no tests.
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadocs, as appropriate.
- [ ] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")`, if applicable.
- [ ] UI changes do not introduce regressions when enforcing the current default rules of [Content Security Policy Plugin](https://plugins.jenkins.io/csp/). In particular, new or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content Security Policy (CSP) directives (see [documentation](https://www.jenkins.io/doc/developer/security/csp/)).
- [ ] For dependency updates, there are links to external changelogs and, if possible, full differentials.
- [ ] For new APIs and extension points, there is a link to at least one consumer.

### Desired reviewers

@mention

Before the changes are marked as `ready-for-merge`:

### Maintainer checklist

- [ ] There are at least two (2) approvals for the pull request and no outstanding requests for change.
- [ ] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [ ] Changelog entries in the pull request title and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [ ] Proper changelog labels are set so that the changelog can be generated automatically.
- [ ] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [ ] If it would make sense to backport the change to LTS, be a _Bug_ or _Improvement_, and either the issue or pull request must be labeled as `lts-candidate` to be considered.

### CODE REVIEW

File: war/src/main/webapp/scripts/hudson-behavior.js [hunk 1]
```diff
@@ -1705,25 +1705,38 @@ function rowvgStartEachRow(recursive, f) {
...
           if (show) {
-            renderOnDemand(f.nextElementSibling);
+            const idx = i; // capture the index so that it is not mutated in the loop
+            renderOnDemand(f.nextElementSibling, function () {
+              var current = e.selectedIndex == idx;
+              if (!current) {
+                console.log(
+                  "**** renderOnDemandCallback, selection no longer valid, form submission would have been corrupted",
+                );
+                updateDropDownFormRowVisibility(f, false);
```
Comment (jtnord) [inline war/src/main/webapp/scripts/hudson-behavior.js]: Whilst I am confident this is the cause of the issue - this does not fix it (not sure why).

the entry is printed yet the form for username/password that should be disabled (as we have chosen `SSH Username with private key` remains like the following when debugged in `buildForm`  (  `console.log("BuildFormTree with form -> ", getHTML(form));`)


```
          <div width="100%" name="credentials" path="/credentials">
            <div class="dropdownList-start rowvg-start tr form-container--hidden" style="display: none;"
              field-disabled="true"></div>
            <div class="jenkins-form-item tr ">
```

this third div should have become:
```
             <div class="jenkins-form-item tr form-container--hidden" style="display: none;" field-disabled="true">
```

Comment (jtnord) [reply war/src/main/webapp/scripts/hudson-behavior.js]: because `renderOnDemand` takes `f` and trashes it completely rather than updating it inplace, so we are manipulating something that is not attached to the dom

```
    while (c.firstElementChild != null) {
      var n = c.firstElementChild;
      e.parentNode.insertBefore(n, e);
      if (n.nodeType == 1 && !noBehaviour) {
        elements.push(n);
      }
    }
    e.remove();
```

so will need to go and reparse the dropdown to get the new bits for the current index...

Comment (timja) [reply war/src/main/webapp/scripts/hudson-behavior.js]: what about modifying renderOnDemand instead, could potentially:
- abort outstanding requests when invalidated?
- pass another function to allow checking the update is valid before it changes the DOM?

Comment (jtnord) [reply war/src/main/webapp/scripts/hudson-behavior.js]: > what about modifying renderOnDemand instead, could potentially

renderOnDemand runs an arbirary function that is defined somewhere for some form parts and attached as a reference in `window`  (here be dragons) and this has a large blast radius.

> pass another function to allow checking the update is valid before it changes the DOM?

possible, `renderOnDemand` is used in a lot of places though.

I hope I have a solution (testing at the moment), it still uses the callback from `renderOnDemand`  but it finds the correct form part again, so this should get the newly added bits, and should then be correctly able to hide them.  This callback should be synchronous with the update of the DOM so we "should be fine"™️

https://github.com/jenkinsci/jenkins/blob/03eaf02824164bc6b187127003dde5d9afd893e9/war/src/main/webapp/scripts/hudson-behavior.js#L1719-L1721

Comment (jtnord) [reply war/src/main/webapp/scripts/hudson-behavior.js]: looking good, currently passed 14 times and the `selection no longer valid, form submission would have been corrupted` warning has been printed 5 times.
Will leave this looping overnight and 🤞 will all pass (or at least it will not have failed due to form corruption)

File: war/src/main/webapp/scripts/hudson-behavior.js [hunk 2]
```diff
@@ -1683,47 +1683,66 @@ function rowvgStartEachRow(recursive, f) {
...
+            const idx = i; // capture the index so that it is not mutated in the loop
+            renderOnDemand(f.nextElementSibling, function () {
+              var current = e.selectedIndex == idx;
+              if (!current) {
+                console.log(
+                  "**** renderOnDemandCallback, selection no longer valid, form submission would have been corrupted",
+                );
+                // our form div has changed (but the index is stable) so go and re-get the new domtree
+                var subForm = buildSubForms(e)[idx];
+                updateDropDownFormRowVisibility(subForm, false);
```
Comment (jtnord) [inline war/src/main/webapp/scripts/hudson-behavior.js:1721]: for testing these 3 lines where commented out to show the previous console line was printed and the test failed ~ 1:10
Then re introduced and the test passed 100 times in a row

File: war/src/main/webapp/scripts/hudson-behavior.js [hunk 3]
```diff
@@ -1683,47 +1683,66 @@ function rowvgStartEachRow(recursive, f) {
...
       function updateDropDownList() {
         for (var i = 0; i < subForms.length; i++) {
           var show = e.selectedIndex == i;
           var f = subForms[i];
 
           if (show) {
-            renderOnDemand(f.nextElementSibling);
+            const idx = i; // capture the index so that it is not mutated in the loop
+            renderOnDemand(f.nextElementSibling, function () {
+              var current = e.selectedIndex == idx;
```
Comment (timja) [inline war/src/main/webapp/scripts/hudson-behavior.js]: new should should use const or let:
```suggestion
              const current = e.selectedIndex == idx;
```

File: war/src/main/webapp/scripts/hudson-behavior.js [hunk 4]
```diff
@@ -1683,47 +1683,66 @@ function rowvgStartEachRow(recursive, f) {
...
+              if (!current) {
+                console.log(
+                  "**** renderOnDemandCallback, selection no longer valid, form submission would have been corrupted",
+                );
+                // our form div has changed (but the index is stable) so go and re-get the new domtree
+                var subForm = buildSubForms(e)[idx];
```
Comment (timja) [inline war/src/main/webapp/scripts/hudson-behavior.js]: new should should use const or let:

```suggestion
                const subForm = buildSubForms(e)[idx];
```

File: war/src/main/webapp/scripts/hudson-behavior.js [hunk 5]
```diff
@@ -1683,47 +1683,66 @@ function rowvgStartEachRow(recursive, f) {
...
 
           if (show) {
-            renderOnDemand(f.nextElementSibling);
+            const idx = i; // capture the index so that it is not mutated in the loop
+            renderOnDemand(f.nextElementSibling, function () {
+              var current = e.selectedIndex == idx;
+              if (!current) {
+                console.log(
+                  "**** renderOnDemandCallback, selection no longer valid, form submission would have been corrupted",
+                );
```
Comment (timja) [inline war/src/main/webapp/scripts/hudson-behavior.js]: something like:
```suggestion
                console.warn(
                  "renderOnDemandCallback: selection is no longer valid, rebuilding correct DOM",
                );
```

**Review by timja — APPROVED** [review]
Thanks!

File: war/src/main/webapp/scripts/hudson-behavior.js (hunk 1 above)
Comment (jtnord) [reply war/src/main/webapp/scripts/hudson-behavior.js]: overnight this ran 800 times without failure

**Review by janfaracik — APPROVED** [review]

**Review by A1exKH — APPROVED** [review]
LGTM.

**Review by StefanSpieker — APPROVED** [review]
