### PR TITLE
Use system temp directory for CommandInstaller scripts

### LINKED ISSUE #13136: [JENKINS-16005] CommandInstaller assumes write access to installation directory
<p>The Mercurial incorrectly assumes write-access to the Mercurial installation directory, triggering the following exception:</p>

<pre>
hudson.util.IOException2: Failed to create a temp file on /usr
	at hudson.FilePath.createTextTempFile(FilePath.java:1163)
	at hudson.FilePath.createTextTempFile(FilePath.java:1114)
	at hudson.tools.CommandInstaller.performInstallation(CommandInstaller.java:82)
	at hudson.tools.InstallerTranslator.getToolHome(InstallerTranslator.java:61)
	at hudson.tools.ToolLocationNodeProperty.getToolHome(ToolLocationNodeProperty.java:107)
	at hudson.tools.ToolInstallation.translateFor(ToolInstallation.java:203)
	at hudson.plugins.mercurial.MercurialInstallation.forNode(MercurialInstallation.java:103)
	at hudson.plugins.mercurial.MercurialSCM.findHgExe(MercurialSCM.java:201)
	at hudson.plugins.mercurial.HgExe.<init>(HgExe.java:80)
	at hudson.plugins.mercurial.MercurialSCM.clone(MercurialSCM.java:554)
	at hudson.plugins.mercurial.MercurialSCM.checkout(MercurialSCM.java:389)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1324)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:676)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:88)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:581)
	at hudson.model.Run.execute(Run.java:1518)
	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:477)
	at hudson.model.ResourceController.execute(ResourceController.java:88)
	at hudson.model.Executor.run(Executor.java:236)
Caused by: hudson.util.IOException2: remote file operation failed: /usr at hudson.remoting.Channel@​26528fa4:Ubuntu 12.04
	at hudson.FilePath.act(FilePath.java:848)
	at hudson.FilePath.act(FilePath.java:825)
	at hudson.FilePath.createTextTempFile(FilePath.java:1141)
	... 18 more
</pre>

<p>My configuration is as follows:</p>

<p>Installation directory = /usr<br/>
Executable = INSTALLATION/bin/hg<br/>
Installation Automatically using command: "sudo apt-get install mercurial"</p>

<p>Jenkin's user does not have general access to /usr, nor to "sudo". It only has executable permissions in /usr/bin and "sudoers" permission to "apt-get".</p>

<p>Expected behavior: write temporary files into the path specified by the "java.io.tmpdir" system property.</p>

---
<details><summary><i>Originally reported by  <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=cowwoc">cowwoc</a>, imported from: <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-16005" target="_blank">CommandInstaller assumes write access to installation directory</a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Major
<li><b>component(s)</b>: core
<li><b>label(s)</b>: newbie-friendly
<li><b>resolution</b>: Unresolved
<li><b>votes</b>: 0
<li><b>watchers</b>: 4
<li><b>imported</b>: 2025-11-24
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p>The Mercurial incorrectly assumes write-access to the Mercurial installation directory, triggering the following exception:</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">hudson.util.IOException2: Failed to create a temp file on /usr
	at hudson.FilePath.createTextTempFile(FilePath.java:1163)
	at hudson.FilePath.createTextTempFile(FilePath.java:1114)
	at hudson.tools.CommandInstaller.performInstallation(CommandInstaller.java:82)
	at hudson.tools.InstallerTranslator.getToolHome(InstallerTranslator.java:61)
	at hudson.tools.ToolLocationNodeProperty.getToolHome(ToolLocationNodeProperty.java:107)
	at hudson.tools.ToolInstallation.translateFor(ToolInstallation.java:203)
	at hudson.plugins.mercurial.MercurialInstallation.forNode(MercurialInstallation.java:103)
	at hudson.plugins.mercurial.MercurialSCM.findHgExe(MercurialSCM.java:201)
	at hudson.plugins.mercurial.HgExe.&lt;init&gt;(HgExe.java:80)
	at hudson.plugins.mercurial.MercurialSCM.clone(MercurialSCM.java:554)
	at hudson.plugins.mercurial.MercurialSCM.checkout(MercurialSCM.java:389)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1324)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:676)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:88)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:581)
	at hudson.model.Run.execute(Run.java:1518)
	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:477)
	at hudson.model.ResourceController.execute(ResourceController.java:88)
	at hudson.model.Executor.run(Executor.java:236)
Caused by: hudson.util.IOException2: remote file operation failed: /usr at hudson.remoting.Channel@26528fa4:Ubuntu 12.04
	at hudson.FilePath.act(FilePath.java:848)
	at hudson.FilePath.act(FilePath.java:825)
	at hudson.FilePath.createTextTempFile(FilePath.java:1141)
	... 18 more
</pre>
</div></div>

<p>My configuration is as follows:</p>

<p>Installation directory = /usr
Executable = INSTALLATION/bin/hg
Installation Automatically using command: "sudo apt-get install mercurial"</p>

<p>Jenkin's user does not have general access to /usr, nor to "sudo". It only has executable permissions in /usr/bin and "sudoers" permission to "apt-get".</p>

<p>Expected behavior: write temporary files into the path specified by the "java.io.tmpdir" system property.</p></pre>
</details>
</details>

### PR DESCRIPTION
**Pull request by meetgoti07**
Fixes #13136

`AbstractCommandInstaller.performInstallation()` was calling `createTextTempFile()` with the default `inThisDirectory=true`, causing it to create temp script files in the tool's installation directory (e.g., `/usr`). This fails when Jenkins doesn't have write access to that directory.

Changed to use `createTextTempFile(..., false)` to create temp files in the system temp directory (`java.io.tmpdir`) instead.
Added explicit dir.mkdirs() call to ensure the tool installation directory exists before running the script.

### Testing done

Manually tested by:
1. Configured a JDK tool with "Install automatically" using "Run Command"
2. Set Tool Home to `/usr` (a read-only directory on macOS)
3. Created a Freestyle job using this JDK
4. **Before fix**: Build failed with `Failed to create a temp file on /usr`
5. **After fix**: Build succeeded, temp script created in system temp directory (`/var/folders/.../T/hudsonXXX.sh`)

#### Before
Screenshot 2026-02-02 at 12 04 45 AM

#### After
Screenshot 2026-02-02 at 12 05 49 AM

### Proposed changelog entries

- Do not fail builds when the tool installation directory is read-only.

### Proposed changelog category

/label bug

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [x] The issue, if it exists, is well-described.
- [x] The changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developers, depending on the change) and are in the imperative mood (see [examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)). Fill in the **Proposed upgrade guidelines** section only if there are breaking changes or changes that may require extra steps from users during upgrade.
- [x] There is automated testing or an explanation as to why this change has no tests.
- [x] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadocs, as appropriate.
- [x] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")`, if applicable.
- [x] UI changes do not introduce regressions when enforcing the current default rules of [Content Security Policy Plugin](https://plugins.jenkins.io/csp/). In particular, new or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content Security Policy (CSP) directives (see [documentation](https://www.jenkins.io/doc/developer/security/csp/)).
- [x] For dependency updates, there are links to external changelogs and, if possible, full differentials.
- [x] For new APIs and extension points, there is a link to at least one consumer.

### Desired reviewers
@daniel-beck @krisstern 

Before the changes are marked as `ready-for-merge`:

### Maintainer checklist

- [ ] There are at least two (2) approvals for the pull request and no outstanding requests for change.
- [x] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [x] Changelog entries in the pull request title and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [x] Proper changelog labels are set so that the changelog can be generated automatically.
- [ ] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [ ] If it would make sense to backport the change to LTS, be a _Bug_ or _Improvement_, and either the issue or pull request must be labeled as `lts-candidate` to be considered.

### CODE REVIEW

**Comment by meetgoti07** [comment]
Hi @MarkEWaite,

Just a gentle reminder on the PR whenever you have a chance.

I have addressed the previous feedback, avoided force pushing, and fixed the test failure issue. I would really appreciate your review when it fits your schedule.

Thank you.

**Review by MarkEWaite — APPROVED** [review]
I confirmed that the bug can be duplicated without this fix and that it is resolved with the fix.

The automated test fails without this fix and passes with it.

This PR is now ready for merge. We will merge it after the security release if there is no negative feedback.

/label ready-for-merge

**Review by A1exKH — APPROVED** [review]
LGTM.

File: test/src/test/java/hudson/tools/CommandInstallerTest.java [hunk 1]
```diff
@@ -25,4 +37,19 @@ void validateCommandInstallerCommandEOL() {
...
+
+    @Issue("https://github.com/jenkinsci/jenkins/issues/13136")
+    @Test
+    void commandInstallerDoesNotRequireWritePermissionOnToolDir() throws Exception {
+        String javaHome = "/opt/jdk-25"; // ci.jenkins.io Java 25 directory
+        File javaHomeDir = new File(javaHome);
+        // Use a Unix installation dir that exists and is not writeable
+        assumeTrue(javaHomeDir.exists(), "No java home directory '" + javaHome + "'");
+        assumeTrue(!Functions.isWindows());
+        assumeTrue(!Files.isWritable(javaHomeDir.toPath()), "Java home directory '" + javaHome + "' is writable");
```
Comment (daniel-beck) [inline test/src/test/java/hudson/tools/CommandInstallerTest.java]: Why not `assumeFalse` here?

File: core/src/main/java/hudson/tools/AbstractCommandInstaller.java [hunk 2]
```diff
@@ -72,8 +72,9 @@ public String getToolHome() {
     @Override
     public FilePath performInstallation(ToolInstallation tool, Node node, TaskListener log) throws IOException, InterruptedException {
         FilePath dir = preferredLocation(tool, node);
+        dir.mkdirs();
```
Comment (daniel-beck) [inline core/src/main/java/hudson/tools/AbstractCommandInstaller.java:75]: Why add this if you're not using the directory anyway?

Comment (MarkEWaite) [reply core/src/main/java/hudson/tools/AbstractCommandInstaller.java:75]: The `InstallerTranslatorTest.testNoMessageLoggedWhenAnyInstallerFound ` and `InstallerTranslatorTest.multipleSlavesAndTools` [tests](https://ci.jenkins.io/job/Core/job/jenkins/job/PR-26240/3/testReport/) fail without this change.  Failure message is:

```
java.io.IOException: Process working directory '/home/jenkins/agent/workspace/Core_jenkins_PR-26240/test/target/j h4387705079793496733/agent-work-dirs/slave0/tools/hudson.model.JDK/jdk1' doesn't exist!
 at app//hudson.Proc$LocalProc.<init>(Proc.java:247)
```

File: test/src/test/java/hudson/tools/CommandInstallerTest.java (hunk 1 above)
Comment (MarkEWaite) [reply test/src/test/java/hudson/tools/CommandInstallerTest.java]: I'm happy to change it to assumeFalse.  I wrote it as `assumeTrue` because I thought it was a little more readable to have the sequence of 3 `assumeTrue` statements.  I'm not deeply attached to that idea, it just seemed easier at the time I was writing it.

I used 3 separate `assume` statements so that the expected skip of the Windows test would use the default message and the other 2 conditions would hopefully identify to someone that there was a surprise in the test environment.

An additional assumeTrue could be added to only run the test on ci.jenkins.io, but I didn't see the risk of allowing the test to run elsewhere if the other pre-conditions are satisfied.

Comment (MarkEWaite) [reply test/src/test/java/hudson/tools/CommandInstallerTest.java]: Fixed in f2577d9cdd
