### PR TITLE
Fix race condition during initial admin account creation

### LINKED ISSUE #26027: Race condition in HudsonPrivateSecurityRealm.doCreateFirstAccount allows multiple initial admin accounts
### Jenkins and plugins versions report

  <details>
    <summary>Environment</summary>

     Jenkins: 2.545-SNAPSHOT
     OS: Linux - 6.12.11-200.fc41.x86_64
     Java: 25.0.1 - Red Hat, Inc. (OpenJDK 64-Bit Server VM)
     ---
     antisamy-markup-formatter:173.v680e3a_b_69ff3
     asm-api:9.9-185.va_6c6b_3348b_c3
     bootstrap5-api:5.3.8-895.v4d0d8e47fea_d
     bouncycastle-api:2.30.1.82-277.v70ca_0b_877184
     caffeine-api:3.2.3-194.v31a_b_f7a_b_5a_81
     checks-api:373.vfe7645102093
     cloudbees-folder:6.1073.va_7888eb_dd514
     commons-lang3-api:3.20.0-109.ve43756e2d2b_4
     commons-text-api:1.15.0-210.v7480a_da_70b_9e
     credentials:1453.v9b_a_29777a_b_fd
     display-url-api:2.217.va_6b_de84cc74b_
     echarts-api:6.0.0-1165.vd1283a_3e37d4
     font-awesome-api:7.1.0-882.v1dfb_771e3278
     instance-identity:203.v15e81a_1b_7a_38
     ionicons-api:94.vcc3065403257
     jackson2-api:2.19.2-408.v18248a_324cfe
     jquery3-api:3.7.1-594.vb_3864f326cf0
     junit:1380.v491ff054cd35
     mailer:525.v2458b_d8a_1a_71
     matrix-auth:3.2.9
     matrix-project:870.v9db_fcfc2f45b_
     plugin-util-api:6.1192.v30fe6e2837ff
     prism-api:1.30.0-630.va_e19d17f83b_0
     scm-api:724.v7d839074eb_5c
     script-security:1385.v7d2d9ec4d909
     structs:362.va_b_695ef4fdf9
     variant:70.va_d9f17f859e0
     workflow-api:1398.v67030756d3fb_
     workflow-step-api:710.v3e456cc85233
     workflow-support:1010.vb_b_39488a_9841

  </details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Fedora 43

### Reproduction steps

   1. Initialize a clean Jenkins installation using `HudsonPrivateSecurityRealm` as the security realm.
   2. Ensure no user accounts have been created yet (initial setup state).
   3. Simultaneously send multiple concurrent POST requests to the `/securityRealm/createFirstAccount` endpoint with different usernames and valid account details.
   4. Verify the number of users created and their permissions.

### Expected Results

Only the very first request should succeed in creating an account. All subsequent concurrent requests should fail with a 401 Unauthorized error (or similar) because a user already exists or is being created, preventing the creation of multiple initial administrator accounts.

### Actual Results

A race condition exists in `HudsonPrivateSecurityRealm.doCreateFirstAccount`. The `hasSomeUser()` check is non-atomic and unsynchronized. In testing with 20 concurrent threads, 20 different user accounts were created, and all 20 were granted administrative privileges via `tryToMakeAdmin(u)`.

### Anything else?

The vulnerability is a classic Time-of-Check to Time-of-Use race condition in `core/src/main/java/hudson/security/HudsonPrivateSecurityRealm.java` between lines 366-376. While impact is limited to the initial setup phase, it allows an attacker to gain admin access if they can time requests during the window before the first user is fully persisted.

### Are you interested in contributing a fix?

Yes, the fix involves adding a static lock object to synchronize the `doCreateFirstAccount` method. This ensures the `hasSomeUser()` check and subsequent user creation are atomic.

### PR DESCRIPTION
**Pull request by ghost**
Fixes #26027

### Testing done

This change was tested by reproducing the reported race condition with
multiple concurrent POST requests to `/securityRealm/createFirstAccount`
during initial setup.
Before the fix, concurrent requests could create multiple users with
administrative privileges. After synchronizing the account creation
logic, only the first request succeeds and all subsequent concurrent
requests fail with an unauthorized error.
Due to the nature of the issue (concurrent HTTP requests during the
initial setup phase), automated test coverage is non-trivial and was
not added as part of this change.

### Proposed changelog entries

- Prevent race condition during initial administrator account creation.

### Proposed changelog category

/label bug

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [x] The issue, if it exists, is well-described.
- [x] The changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developers, depending on the change) and are in the imperative mood (see [examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)). Fill in the **Proposed upgrade guidelines** section only if there are breaking changes or changes that may require extra steps from users during upgrade.
- [x] There is automated testing or an explanation as to why this change has no tests.
- ~New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadocs, as appropriate.~
- ~New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")`, if applicable.~
- ~UI changes do not introduce regressions when enforcing the current default rules of [Content Security Policy Plugin](https://plugins.jenkins.io/csp/). In particular, new or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content Security Policy (CSP) directives (see [documentation](https://www.jenkins.io/doc/developer/security/csp/)).~
- ~For dependency updates, there are links to external changelogs and, if possible, full differentials.~
- ~For new APIs and extension points, there is a link to at least one consumer.~

### Desired reviewers

@jenkinsci/core-pr-reviewers

Before the changes are marked as `ready-for-merge`:

### Maintainer checklist

- [ ] There are at least two (2) approvals for the pull request and no outstanding requests for change.
- [ ] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [x] Changelog entries in the pull request title and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [x] Proper changelog labels are set so that the changelog can be generated automatically.
- ~If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).~
- ~If it would make sense to backport the change to LTS, be a _Bug_ or _Improvement_, and either the issue or pull request must be labeled as `lts-candidate` to be considered.~

### CODE REVIEW

**Review by MarkEWaite — APPROVED** [review]
Thanks!  The change looks good to me.

I performed a few simple interactive tests of the setup wizard with this pull request and found no issues.  I tested creating a new user in the setup wizard and skipping the user creation in the setup wizard.

Thanks very much for the excellent description in the pull request and for your testing to confirm it is well behaved after the change.

GitHub Copilot review noted that a similar race condition exists in the `_doCreateAccount` method, but that method only attempts to create a new user if signup is allowed and will only grant admin to the created user if it is the first user created.  The initial configuration does not allow signup, so there is no chance for the race condition in `_doCreateAccount` to be exercised.  

I was impressed that GitHub Copilot looked outside the diff and even more pleased that it decided to not make any visible comment outside the diff.

File: core/src/main/java/hudson/security/HudsonPrivateSecurityRealm.java [hunk 1]
```diff
@@ -356,25 +356,34 @@ private String getErrorMessages(SignupInfo si) {
...
+            }
+            User u = createAccount(req, rsp, false, "firstUser.jelly");
+            if (u != null) {
+                tryToMakeAdmin(u);
+                loginAndTakeBack(req, rsp, u);
+            }
         }
     }
 
+
```
[the remark this answers is not in the document]
Comment (MarkEWaite) [reply core/src/main/java/hudson/security/HudsonPrivateSecurityRealm.java]: This Copilot comment is correct but entirely optional

File: core/src/main/java/hudson/security/HudsonPrivateSecurityRealm.java [hunk 2]
```diff
@@ -356,25 +356,34 @@ private String getErrorMessages(SignupInfo si) {
...
-            rsp.sendError(SC_UNAUTHORIZED, "First user was already created");
-            return;
-        }
-        User u = createAccount(req, rsp, false, "firstUser.jelly");
-        if (u != null) {
-            tryToMakeAdmin(u);
-            loginAndTakeBack(req, rsp, u);
+    public void doCreateFirstAccount(StaplerRequest2 req, StaplerResponse2 rsp)
+            throws IOException, ServletException {
+        synchronized (CREATE_FIRST_ACCOUNT_LOCK) {
```
Comment (mawinter69) [inline core/src/main/java/hudson/security/HudsonPrivateSecurityRealm.java]: Wouldn't it be sufficient to make the method `synchronized`. Avoids creating a dedicated object

Comment (ghost) [reply core/src/main/java/hudson/security/HudsonPrivateSecurityRealm.java]: Good question.
Yes, marking the method itself as `synchronized` would also prevent the race
condition and would be functionally equivalent in this case.

I opted for an explicit static lock to keep the synchronization scope very
clear and localized to the critical section, and to avoid synchronizing the
entire method implicitly in case additional logic is added later.
That said, I don’t have a strong preference here — if the maintainers would
rather switch to a `synchronized` method for simplicity, I’m happy to adjust.

File: core/src/main/java/hudson/security/HudsonPrivateSecurityRealm.java (hunk 1 above)
[the remark this answers is not in the document]
Comment (ghost) [reply core/src/main/java/hudson/security/HudsonPrivateSecurityRealm.java]: it's done

**Comment by Pnkcaht** [comment]
Thanks everyone for the review and feedback.
I’ve addressed the minor formatting suggestion and updated the pull request accordingly.

I really appreciate the time spent reviewing and testing this change, as well as the additional context shared during the discussion. I’m happy to continue contributing and appreciate the work you all do maintaining Jenkins.

**Review by MarkEWaite — APPROVED** [review]

**Review by MarkEWaite — APPROVED** [review]
This PR is now ready for merge. We will merge it after approximately 24 hours if there is no negative feedback.

/label ready-for-merge

File: core/src/main/java/hudson/security/HudsonPrivateSecurityRealm.java (hunk 2 above)
Comment (timja) [reply core/src/main/java/hudson/security/HudsonPrivateSecurityRealm.java]: please just add `synchronized` to the method.

Comment (ghost) [reply core/src/main/java/hudson/security/HudsonPrivateSecurityRealm.java]: Done — switched to a synchronized method as suggested. @timja 
```java
    /**
     * Creates a first admin user account.
     *
     * <p>
     * This can be run by anyone, but only to create the very first user account.
     */
    @RequirePOST
    public synchronized void doCreateFirstAccount(StaplerRequest2 req, StaplerResponse2 rsp)
            throws IOException, ServletException {

        if (hasSomeUser()) {
            rsp.sendError(SC_UNAUTHORIZED, "First user was already created");
            return;
        }

        User u = createAccount(req, rsp, false, "firstUser.jelly");
        if (u != null) {
            tryToMakeAdmin(u);
            loginAndTakeBack(req, rsp, u);
        }
    }
```

**Comment by MarkEWaite** [comment]
Fixed in https://www.jenkins.io/changelog/2.545/
