### PR TITLE
fix: prevent autocomplete selection from submitting form

### LINKED ISSUE #26639: Selecting an autocomplete suggestion submits the entire configuration form
### Jenkins and plugins versions report

2.559
Firefox

### What Operating System are you using (both controller, and any agents involved in the problem)?

Docker container

### Reproduction steps

1. http://localhost:8081/manage/log/
2. `+ Add Recorder`
3. "Foo"
4. (Enter)
5. `+ Add`
6. Type "core"
7. Select the first autocompletion entry

### Expected Results

it autocompletes the text field

### Actual Results

That, and it submits the form. I wasn't done yet!

### Anything else?

_No response_

### Are you interested in contributing a fix?

_No response_

### PR DESCRIPTION
**Pull request by Wassef-Chebbi**
# Fixes #26639

Dropdown <button> elements in the template lacked type="button", causing browsers to default them to type="submit" inside configuration forms. Clicking an autocomplete suggestion would therefore trigger an unintended form submission.
The fix sets type="button" at the template level in templates.js, covering all affected dropdowns globally — including the autocomplete and combo-box dropdowns mentioned in the issue.

## Testing done

Manually tested in Firefox and Chrome by opening the Log Recorder configuration UI (/manage/log/), typing a partial value to trigger autocomplete, then selecting a suggestion via mouse click and Enter key. Verified the text field was populated and the form was not submitted. Also tested the "Build other projects" post-build action dropdown.

## Screenshots (UI changes only)

Screenshot from 2026-04-16 10-40-32

## Proposed changelog entries

- Prevent selecting an autocomplete suggestion submitting the configuration form

## Proposed changelog category
/label bug, web-ui

## Proposed upgrade guidelines

N/A

## Desired reviewers

@daniel-beck @timja

### CODE REVIEW

**Comment by timja** [comment]
Do we know that this is a regression? Nothing in @daniel-beck's issue suggests it is, we normally just categorise it as a bug if-so.

File: .gitignore [hunk 1]
```diff
@@ -77,3 +77,4 @@ node_modules/
 
 # Generated JavaScript Bundles
 war/src/main/webapp/jsbundles/
+.idea/
```
Comment (timja) [inline .gitignore]: we have multiple .idea files committed you can't just add this to gitignore like this

**Review by timja — CHANGES_REQUESTED** [review]
Doesn't seem to work at all. PR description doesn't map to whats been committed at all

File: src/main/js/components/dropdowns/templates.js [hunk 2]
```diff
@@ -166,7 +166,7 @@ function menuItem(dropdownItem, type = "jenkins-dropdown__item", context = "") {
     );
 
     const button = createElementFromHtml(
-      `<button class="${clazz}"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="48" d="M112 184l144 144 144-144"/></svg></button>`,
+      `<button type="button" class="${clazz}"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="48" d="M112 184l144 144 144-144"/></svg></button>`,
     );
     Utils.generateDropdown(
```
[the remark this answers is not in the document]
Comment (Wassef-Chebbi) [reply src/main/js/components/dropdowns/templates.js:171]: Updated — type="button" is now set on all dropdown button items in the main menu item template as well.

**Comment by Wassef-Chebbi** [comment]
> Doesn't seem to work at all. PR description doesn't map to whats been committed at all

Sorry for the confusion, the description was outdated. The actual fix sets type="button" on all dropdown button elements in templates.js. I've updated the description to match what's been committed.

File: .idea/.name
Comment (timja) [inline .idea/.name:1]: why are you deleting these files

Comment (Wassef-Chebbi) [reply .idea/.name:1]: Sorry about that , I've restored the .idea files to their original state. The deletion was unintentional, caused by my local IntelliJ setup. They're back now and the PR only touches templates.js.

**Review by timja — APPROVED** [review]
Seems fine, manually tested log records and "Build other projects" in freestyle builds.

Thanks!

**Comment by daniel-beck** [comment]
> Do we know that this is a regression? Nothing in @daniel-beck's issue suggests it is, we normally just categorise it as a bug if-so.

Other than the `regression` label? 😁 

https://github.com/jenkinsci/jenkins/issues/26639#issuecomment-4260844894

**Comment by timja** [comment]
> > Do we know that this is a regression? Nothing in @daniel-beck's issue suggests it is, we normally just categorise it as a bug if-so.
> 
> Other than the `regression` label? 😁
> 
> [#26639 (comment)](https://github.com/jenkinsci/jenkins/issues/26639#issuecomment-4260844894)

I've made the regression label red now so it stands out, missed that before.

File: src/main/js/components/dropdowns/templates.js
Comment (janfaracik) [inline src/main/js/components/dropdowns/templates.js]:
```suggestion
     <${tag}
       ${optionalVals({
         class: clazz,
         href: url,
         id: itemOptions.id,
         "data-html-tooltip": itemOptions.tooltip,
         type: tag === "button" ? "button" : null,
       })}>
```

Not tested but this should work?

**Review by janfaracik — APPROVED** [review]
One comment - otherwise LGTM, thanks!

**Comment by janfaracik** [comment]
/label ready-for-merge

----

This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!
