### PR TITLE
Don't validate input fields when they are disabled

### LINKED ISSUE #26297: A disabled checkbox is still running field validation
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
Jenkins 2.550
Mailer plugin 525.v2458b_d8a_1a_71
extended-read-permissions
matrix-auth
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

not relevant

### Reproduction steps

1. Install https://plugins.jenkins.io/extended-read-permission/
2. Configure Jenkins with built-in user database
3. install matrix auth plugin and enable it
4. create and configure a user to have the permissions Overall/Read and Overall/SystemRead
5. As that user visit Manage Jenkins -> System

### Expected Results

The user can see the all configuration that a user with SystemRead should see

### Actual Results

The user is redirected to the login page. In the Jenkins log there is the message
```
[INFO] While serving http://localhost:8080/jenkins/manage/descriptorByName/hudson.tasks.Mailer/checkAuthentication: hudson.security.AccessDeniedException3: tester is missing the Overall/Manage permission
```

### Anything else?

Root cause is that for a checkbox the field validation is still performed even when the checkbox is disabled. While usually a checkbox doesn't validation there can still be situations where a plugin uses `f:optionalProperty` which uses a checkbox and then performs validation on that optional property including and fields that are included from that optional property as done in the mailer plugin. When the plugin is then throwing an error due to missing permissions, the page is not loading and the user with read only permissions is redirected to the login page.

Relates to https://github.com/jenkinsci/mailer-plugin/issues/615

### Are you interested in contributing a fix?

_No response_

### PR DESCRIPTION
**Pull request by mawinter69**
Fix a problem where disabled checkboxes still call the checkUrl endpoint to validate the field. When that validation throws an exception, e.g. due to missing permissions (user has SYSTEM_READ), the user is redirected to the login page instead of being able to see the corresponding config page.

fixes #26297

### Testing done
1. Install https://plugins.jenkins.io/extended-read-permission/
2. Configure Jenkins with built-in user database
3. Install matrix auth plugin and enable it
4. create and configure a user to have the permissions Overall/Read and Overall/SystemRead
5. As that user visit Manage Jenkins -> System
6. The page no longer redirects to login page

### Proposed changelog entries

- Don't validate input fields when they are disabled

### Proposed changelog category

/label bug

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [x] The issue, if it exists, is well-described.
- [x] The changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developers, depending on the change) and are in the imperative mood (see [examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)). Fill in the **Proposed upgrade guidelines** section only if there are breaking changes or changes that may require extra steps from users during upgrade.
- [ ] There is automated testing or an explanation as to why this change has no tests.
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadocs, as appropriate.
- [ ] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")`, if applicable.
- [ ] UI changes do not introduce regressions when enforcing the current default rules of [Content Security Policy Plugin](https://plugins.jenkins.io/csp/). In particular, new or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content Security Policy (CSP) directives (see [documentation](https://www.jenkins.io/doc/developer/security/csp/)).
- [ ] For dependency updates, there are links to external changelogs and, if possible, full differentials.
- [ ] For new APIs and extension points, there is a link to at least one consumer.

### Desired reviewers

@mention

Before the changes are marked as `ready-for-merge`:

### Maintainer checklist

- [ ] There are at least two (2) approvals for the pull request and no outstanding requests for change.
- [ ] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [ ] Changelog entries in the pull request title and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [ ] Proper changelog labels are set so that the changelog can be generated automatically.
- [ ] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [ ] If it would make sense to backport the change to LTS, be a _Bug_ or _Improvement_, and either the issue or pull request must be labeled as `lts-candidate` to be considered.

### CODE REVIEW

File: war/src/main/webapp/scripts/hudson-behavior.js [hunk 1]
```diff
@@ -699,6 +701,9 @@ function registerValidator(e) {
   }
 
   var checker = function () {
+    if (e.disabled) {
```
Comment (timja) [inline war/src/main/webapp/scripts/hudson-behavior.js]: this doesn't seem to exist by looking at the test failures.

Reading the code it might be this (needs testing though):

```suggestion
    if (this.disabled) {
```

**Review by timja — APPROVED** [review]
Looks sensible

**Review by NotMyFault — APPROVED** [review]

**Review by janfaracik — APPROVED** [review]
/label ready-for-merge

----

This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

**Review by A1exKH — APPROVED** [review]
LGTM.
